#    Postgresql database.yml file
common: &common
  adapter: postgresql
  username: 'berliblog'
  password: 'berliblog'
  host: localhost
  pool: 5

development:
  <<: *common
  adapter: postgresql
  username: 'berliblog'
  password: 'berliblog'
  database: berliblog_development

test:
  <<: *common
  adapter: postgresql
  username: 'berliblog'
  password: 'berliblog'
  database: berliblog_test

production:
  <<: *common
  adapter: postgresql
  username: 'berliblog'
  password: 'berliblog'
  database: berliblog_production
