#    Postgresql database.yml file
common: &common
  encoding: utf8
  adapter: postgresql
  pool: 5
  host: localhost

development:
  <<: *common
  database: berliblog_development

test:
  <<: *common
  database: berliblog_test

production:
  <<: *common
  database: berliblog_production
